### ISSUE TITLE
[Suggestion] add gluetun

### ISSUE THREAD

**Issue by RobotsAreCrazy** [d3vilh/raspberry-gateway#14]
The only thing i think is missing is something like gluetun https://github.com/qdm12/gluetun

thanks 👌

P.S.

Could control-d https://kb.controld.com/tutorials/linux 
be used in place of pihole and if so how would that be integrated into everything?

**Comment by d3vilh** [comment]
Hi @RobotsAreCrazy.
gluetun looks neat, I'll check it and include in future version.

control-d is a commercial app. so until they donate I won't include them :)
If seriously - with Pi-hole/TechDNS and VPN you can achieve the same results. The only one thing will be missed is rules scheduling, whats kind of OK-OK. But let's keep an eye on them, maybe some day in the future.

Thanks for the suggestions!

**Comment by RobotsAreCrazy** [comment]
> Hi @RobotsAreCrazy.
> gluetun looks neat, I'll check it and include in future version.
> 
> control-d is a commercial app. so until they donate I won't include them :)
> If seriously - with Pi-hole/TechDNS and VPN you can achieve the same results. The only one thing will be missed is rules scheduling, whats kind of OK-OK. But let's keep an eye on them, maybe some day in the future.
> 
> Thanks for the suggestions!

Hi, thanks it is just because not long ago i got a 5 year 'some control' control-d subscription from stacksocial so i would like to put it to some use

**Comment by d3vilh** [comment]
> Defintely, gluetun though as it will be useful for those that torrent or stream

I just merge latest dev branch changes with main and we now have legit **Gluetun** container which at the moment supports OpenVPN connections only, what should be enough for testing. 
**qBitTorrent** container was updated to support Gluetun and new **webinstall** binary as well.

Personally during the tests I switched to `webinstall` completely, as it makes configuration more enjoy-full and very easy :D

@RobotsAreCrazy and @fellowape  appreciate if you guys could join internal testing and share your experience with it.

Thanks a lot!

**Comment by RobotsAreCrazy** [comment]
Wireguard is still more performant important on devices like raspberry pi

**Comment by d3vilh** [comment]
> Wireguard is still more performant important on devices like raspberry pi

Agree, it will be the next step. OpenVPN is wider supported by VPN providers that is why chance to test everything with it is wider too. 

Wireguard its on the way too.

**Comment by RobotsAreCrazy** [comment]
So do I just follow install instructions as outlined to get it going?

**Comment by d3vilh** [comment]
> So do I just follow install instructions as outlined to get it going?

yes, same way as Wireguard, or just use `./webinstall` it should deliver with few clicks (check Ansible user there if you have other than just `pi`).

**Comment by RobotsAreCrazy** [comment]
> > So do I just follow install instructions as outlined to get it going?
> 
> yes, same way as Wireguard, or just use `./webinstall` it should deliver with few clicks (check Ansible user there if you have other than just `pi`).

So do I clone, make any config changes then use webinstall?

**Comment by d3vilh** [comment]
> So do I clone, make any config changes then use webinstall?

yes, you just clone it and run ./webinstall it will run web interface for you.

> If you can get wireguard going I will test it I have no doubt it will all work, just I prefer wireguard

I'll include it in future versions, its just need more work, due to specific of configuration and some smart logic update under the hood (OpenVPN have just 4 static parameters to pass into container, while for Wireguard, I have to deploy on the fly other container to define server ID then take it and pass as parameter to other container). I just need to think how to implement it simple way without consuming additional RPI resources.

> How do you get gluetun working with all of this?

Win separate subnet, I just announce it and route all the traffic/ports via this dedicated subnet.

**Comment by RobotsAreCrazy** [comment]
Let me know if you manage wireguard and I will give it a shot

**Comment by d3vilh** [comment]
> Let me know if you manage wireguard and I will give it a shot

What Wireguard provider you would use for testing?
In `gluetunwireguard` branch I have already drafted container.  
As minimum configuration you'll need:
* `wireguard_private_key` in base 58 format 
* `wireguard_address` just regular IP

With this it should connect. Note, I never run it on test env yet, probably, but probably in few hours I'll do :)

**Comment by RobotsAreCrazy** [comment]
Well, I'm either going back to Torguard dedicated IP or paying for windscribe residential IP

**Comment by d3vilh** [comment]
> How's the general wireguard progress going for setting it up through gui etc for wireguard server?

I'll update `webinstall` with additional Gluetun parameters soon, right after containers will be tested.
As of now, only the manual configuration is ready (`config.yml`),  following Gluetun options can be passed to container:
```bash
#    _____ _         _____         
#   |   __| |_ _ ___|_   _|_ _ ___ 
#   |  |  | | | | -_| | | | | |   |
#   |_____|_|___|___| |_| |___|_|_|
#   Universal VPN Client for multiple VPN Providers
#
# TESTING! DO NOT USE ON PRODUCTION!               

gluetun_vpnclient_enable: false                 # Set true to enable Gluetun
gluetun_server_countries: "Netherlands"         # Comma separated list of countries
gluetun_server_cities: "Amsterdam"              # Comma separated list of cities
gluetun_server_update_per: 24h                  # Period to update your servers list using the built-in Gluetun update mechanisms. 
                                                # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
gluetun_vpn_service_provider: nordvpn           # Set your VPN provider: cyberghost, expressvpn, fastestvpn, hidemyass, ipvanish, ivpn, nordvpn, perfect privacy, privado, private internet access, privatevpn, protonvpn, purevpn, slickvpn, surfshark, torguard, vpnsecure, vpn unlimited, vyprvpn, wevpn, windscribe
                                                # See the list of all providers https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
gluetun_vpn_type: wireguard                     # Set your VPN type: openvpn, wireguard

# OPENVPN PART:
gluetun_openvpn_user: "SecretUser"              # Set your OpenVPN username
gluetun_openvpn_password: "gagaZush"            # Set your OpenVPN password
gluetun_vpnclient_custom: false                 # Set true to enable custom OpenVPN configuration below
gluetun_openvpn_custom_conf: "ovpn-custom.conf" # Set your OpenVPN custom configuration. See

# WIREGUARD PART:
gluetun_wireguard_private_key: "yCbHtK...X2c="  # Valid base 58 Wireguard Client key. Wireguard client private key to use.
gluetun_wireguard_public_key: "none"            # Valid base 58 Wireguard Server key. Wireguard Server public key to use.
gluetun_wireguard_preshared_key: "none"         #
gluetun_wireguard_address: "10.99.99.99/32"     # Valid IP network interface address in the format xx.xx.xx.xx/xx or ff:ff:ff...:ff/128
gluetun_wireguard_endpoint_ip: "none"           # Valid IP address in the format xx.xx.xx.xx:xxxxx or [ff:ff:ff...:ff]:xxxxx
gluetun_wireguard_endpoint_port: "none"         # Valid port number in the format xxxx
```

Usually only IP and Client Private kay is necessary, but for Torguard, you may need to use rest parameters (just replace `none` with with keys, ports or IPs.

> How's the general wireguard progress going for setting it up through gui etc for wireguard server?
The Wireguard server + webui is ready for couple of months and you can install it via`config.yml`:
```bash
#    _ _ _ _         _____               _ 
#   | | | |_|___ ___|   __|_ _ ___ ___ _| |
#   | | | | |  _| -_|  |  | | | .'|  _| . |
#   |_____|_|_| |___|_____|___|__,|_| |___|
# WireGuard Server configuration.
wireguard_server_enable: true                  # Set true to enable WireGuard
wireguard_password: "gagaZush"                  # !Change this password!
```
or via `webinstall` binary.

> I'm in 2 minds if I should add a GUI to the install...I've just used terminal to do everything

you can keep using cli, its still there and will be as preferable installation option forever. 
I just add webinstall for lazy people, like myself :) It will still run same playbook, showing all the installation logs, like in console, but you have easy configuration option. Try it.

**Comment by RobotsAreCrazy** [comment]
Was on about in general on a new dietpi install with no desktop, just wondering do you think the wireguard server setup is far off getting working?

**Comment by d3vilh** [comment]
> Was on about in general on a new dietpi install with no desktop, just wondering do you think the wireguard server setup is far off getting working?

Yes it is ready, I did not invent bicycle here, I just included [wireguard-ui project](https://github.com/ngoduykhanh/wireguard-ui), which is used by lot of people and very similar to [openvpn-ui](https://github.com/d3vilh/openvpn-ui). 

Also it worked fine during my testing in local environment.

**Comment by d3vilh** [comment]
@RobotsAreCrazy @fellowape I merge Gluetun Wireguard in main branch. it seems works fine.

@fellowape we need `webinstall` to be updated with lot of new options now 📃

**Comment by d3vilh** [comment]
I'm closing it as Implemented. 

For the suggestions we can use Discussions tab.

**Comment by RobotsAreCrazy** [comment]
It's pretty much perfect now, but I would still like a way to use control-d instead of pihole, must be some way how to do it?

**Comment by RobotsAreCrazy** [comment]
Any chance you might consider a bit of a how to for using technitium in a home setup just some settings to get it going please?

**Comment by d3vilh** [comment]
> Any chance you might consider a bit of a how to for using technitium in a home setup just some settings to get it going please?

It's very easy with Webinstall.
You just scroll to _"Local DNS and AD-Blocking"_ then click to _"TechnitiumDNS"_
<img src="https://i.imgur.com/bBKdPKx.png" alt="techdns webinstall" width="410">

You can leave other Technetium DNS options default. Then scroll down to press _"Save"_ and then _"Install"_.
If you are already have Raspberry-Gateway installation, mark, just techDNS, rest checkboxes for other components is better not to touch.

For CLI here is what needs to be in your config.yml:

```yaml
config_dir: "~"
ur_timezone: Europe/Kyiv
unbound_dns_enable: false
unbound_dns_identitiy: unbound-dns
unbound_dns_hide: "yes"
unbound_dns_ipv4: "yes"
unbound_dns_ipv6: "no"
unbound_dns_num_threads: "1"
unbound_dns_upstream_4_pihole: 127.0.0.1#5335
pihole_enable: false
pihole_with_unbound: false
pihole_password: gagaZush
pihole_hostname: pihole
tech_dns_enable: true
tech_dns_password: gagaZush
tech_dns_hostname: tech-dns
tech_dns_ipv6: false
tech_dns_blocking: true
tech_dns_forwarders: 1.1.1.1, 8.8.8.8
tech_dns_forwarder_proto: Https
tech_dns_server: tech-dns
ovpn_server_enable: false
ovpnui_user: admin
ovpnui_password: gagaZush
ovpn_trusted_subnet: 10.0.70.0/24
ovpn_guest_subnet: 10.0.71.0/24
ovpn_home_subnet: 192.168.0.0/24
ovpn_remote: remote 123.234.123.12 12345 udp
ovpn_client_enable: false
ovpn_client_cert: webinstall-client.ovpn
ovpn_client_allowed_subnet: 192.168.88.0/24
ovpn_client_secret: webinstall-credentials.txt
ovpn_client_killswitch: false
wireguard_server_enable: false
wireguard_user: admin
wireguard_password: gagaZush
wireguard_serverurl: wg.example.com
portainer_enable: false
qbittorrent_enable: false
qbittorrent_default_password: adminadmin
qbittorrent_inside_vpn: false
qbittorrent_inside_gluetun: false
qbittorrent_webui_port: "8090"
monitoring_enable: false
monitoring_grafana_admin_password: admin
monitoring_days_keep_interval: 90d
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 30s
openvpn_monitoring_enable: false
pikvm_monitoring_enable: false
pikvm_target_ip: 192.168.88.3
pikvm_web_user: admin
pikvm_web_password: gagaZush
airgradient_monitoring_enable: false
starlink_monitoring_enable: false
starlink_ip: 10.10.10.1
starlink_port: "9817"
shelly_plug_monitoring_enable: false
shelly_plug_hostname: shelly-host-or-ip
shelly_ip: 192.168.88.66
shelly_port: "9924"
shelly_plug_http_username: admin
shelly_plug_http_password: gagaZush
gluetun_vpnclient_enable: false
gluetun_server_countries: Netherlands
gluetun_server_cities: Amsterdam
gluetun_server_update_per: "0"
gluetun_vpn_service_provider: custom
gluetun_vpn_type: choose
gluetun_openvpn_user: none
gluetun_openvpn_password: none
gluetun_vpnclient_custom: false
glue_ovpn_custom_conf: webinstall-client.ovpn
gluetun_wireguard_private_key: yCbHtK...X2c=
gluetun_wireguard_public_key: none
gluetun_wireguard_preshared_key: none
gluetun_wireguard_address: 10.99.99.99/32
gluetun_wireguard_endpoint_ip: none
gluetun_wireguard_endpoint_port: none
```

Pay attention, you can't have Pi-Hole and Unbound to be up and running in the same server at the same time with TechnetiumDNS, because you have to keep Port 53 as DNS resolver port for your clients.

So, you can have Pi-Hole + DNS or TechnitiumDNS at the same time:

```yaml
unbound_dns_enable: false
pihole_enable: false
tech_dns_enable: true
```
