### ISSUE TITLE
rpi_exporter container issue

### ISSUE THREAD

**Issue by RikiCatte** [d3vilh/raspberry-gateway#50]
Hi, I've a problem with rpi_exporter container: 
```
2025/04/29 13:03:18 Error: invalid argument
2025/04/29 13:03:18 http: superfluous response.WriteHeader call from main.main.func1 (main.go:26)
```
This is the `docker-compose.yml` part regarding that service:
```
 rpi_exporter:
    container_name: rpi_exporter
    image: d3vilh/rpi_exporter-arm64:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "9110:9110/tcp"
    networks:
      - back-tier
```

What I've done to try to fix this error:
1. Tried to curl from host system (ubuntu 24.04 server ARM64) to container with `curl http://localhost:9110/metrics`. output:
```
# HELP rpi_vc_revision Firmware revision of the VideoCore device.
# TYPE rpi_vc_revision gauge
rpi_vc_revision 1727096576
# HELP rpi_board_model Board model.
# TYPE rpi_board_model gauge
Internal Server Error
```
_Internal Server Error I assume that is caused by the error above._

2. Tried to modify `docker-compose.yml` adding the following volume mounts: 
```
rpi_exporter:
    container_name: rpi_exporter
    image: d3vilh/rpi_exporter-arm64:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "9110:9110/tcp"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
    networks:
      - back-tier
```

But I'm still getting the same error.
